profiles:
  default: safe
  definitions:
    safe:
      description: "Conservative automation profile"
      toggles:
        idle_only: true
        foreground_required: true
        coordinate_clicks: false
        elevation: false
        network_allow: []
        filesystem_allow: []
    balanced:
      description: "Balanced automation profile"
      toggles:
        idle_only: false
        foreground_required: true
        coordinate_clicks: false
        elevation: false
        network_allow: ["https://example.com"]
        filesystem_allow: ["C:/Automation/Sandbox"]
    unrestricted:
      description: "Full automation profile (use with caution)"
      toggles:
        idle_only: false
        foreground_required: false
        coordinate_clicks: true
        elevation: true
        network_allow: ["*"]
        filesystem_allow: ["*"]
intents:
  directory: C:/Automation/intents
  archive_directory: C:/Automation/intents/archive
recipes:
  directory: agent/examples/recipes
safety:
  panic_hotkey: "ctrl+alt+shift+esc"
features:
  chat_bridge: true
  ocr_intents: true
intent_map:
  export_quotes:
    recipe: ts.web.export_quotes.yml
  browser_open_home:
    recipe: browser.open_home.yml
  browser_focus:
    recipe: browser.focus.yml
  browser_refresh_quotes:
    recipe: browser.refresh_quotes.yml
  browser_close:
    recipe: browser.close.yml
  browser_force_kill:
    recipe: browser.force_kill.yml
  browser_minimize:
    recipe: browser.minimize.yml
  browser_restore:
    recipe: browser.restore.yml
  browser_maximize:
    recipe: browser.maximize.yml
  browser_focus_and_minimize:
    recipe: browser.focus_and_minimize.yml
  browser_open_url:
    recipe: browser.open_url.yml
  app_launch:
    recipe: app.launch.yml
  app_focus:
    recipe: app.focus.yml
  app_minimize:
    recipe: app.minimize.yml
  app_maximize:
    recipe: app.maximize.yml
  app_restore:
    recipe: app.restore.yml
  app_close:
    recipe: app.close.yml
  context_copy_for_llm:
    recipe: context.copy_for_llm.yml
  context_load_llm_response:
    recipe: context.load_llm_response.yml
  app_kill:
    recipe: app.kill.yml
apps:
  notepad:
    description: "Windows Notepad"
    path: "C:/Windows/System32/notepad.exe"
    enabled: true
    window:
      title_match: "Notepad"
      class_match: null
      process_name: "notepad.exe"
  calculator:
    description: "Windows Calculator"
    shell: "calc.exe"
    enabled: true
    window:
      title_match: "Calculator"
      class_match: null
      process_name: "Calculator.exe"
  browser:
    description: "Default system browser"
    path: "C:/Program Files/Google/Chrome/Application/chrome.exe"
    args:
      - "--new-window"
      - "https://example.com"
    enabled: true
    window:
      title_match: ""
      class_match: null
      process_name: "chrome.exe"
llm:
  active_provider: openai_gpt4o
  providers:
    openai_gpt4o:
      type: api
      provider: openai
      model: gpt-4o
      api_key: "${OPENAI_API_KEY}"
state:
  accounts:
    main:
      cash_free: 100000.0
  market:
    session: closed







